app = "app-ventas"
region = "iad"

[build]
  dockerfile = "backend/Dockerfile"
  context = "."

[env]
  NODE_ENV = "production"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script = null

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 5
    timeout = "2s"

[processes]
  app = "node server.js"

[[statics]]
  guest_paths = ["/app/public"]
  handlers = ["fallback"]

[metrics]
  port = 9090
  path = "/metrics"